# Generated by Django 3.2 on 2022-05-16 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0002_answer_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='final',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('Текст', 'Текст'), ('Выбор', 'Выбор')], max_length=20),
        ),
    ]
